Models/Entities/Customer.cs
using Food_Mania.Models.Enum;

namespace Food_Mania.Models.Entities
{
    public class Customer:BaseEntity
    {
        public string UserId { get; set; }
        public User User { get; set; }
        // public string NextOfKin { get; set; }
        public decimal Wallet { get; set; }
        
        // public Gender Gender { get; set; }
        public List<Order> Order { get; set; }
    }
}

Models/Entities/User.cs
using Food_Mania.Models.Enum;

namespace Food_Mania.Models.Entities
{
    public class User: BaseEntity
    {
        public string FirstName { get; set; }
        public string UserName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string Password { get; set; }
        public string AddressId { get; set; }
        public Address Address { get; set; }
        public Role Role { get; set; }
        public Gender Gender { get; set; }
        public Staff Staff { get; set; }
        public Customer Customer { get; set; }




        

    }
}

Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Food_Mania.Models.Dtos;
using Food_Mania.Models.Service.Interface;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Food_Mania.Controllers
{
    // [Route("[controller]")]
    public class CustomerController : Controller
    {

        private readonly ILogger<CustomerController> _logger;
        private readonly ICustomerService _customerService;
        private readonly IFoodService _foodService;
        public CustomerController(ICustomerService customerService, IFoodService foodService, ILogger<CustomerController> logger = null)
        {
            _customerService = customerService;
            _foodService = foodService;
            _logger = logger;
        }



        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Add(CreateCustomerRequestModel model)
        {
            var register = _customerService.Create(model);
            if (register.Status == true)
            {
                TempData["message"] = register.Message;
                return RedirectToAction("Login", "User");
            }
            return StatusCode(406, "Registration Failed. Email may exist already");
        }
        [HttpGet]
        public IActionResult Update(string id)
        {
            var customer = _customerService.GetById(id);
            return View(customer.Data);
        }
        [HttpPost]
        public IActionResult Update(string id, UpdateCustomerRequestModel model)
        {
            var updateModel = _customerService.Update(id, model);
            if (updateModel.Status == true)
            {
                return RedirectToAction("#", "Customer");
            }
            return StatusCode(406, "Update Failed. ");
        }
        [HttpGet]
        public IActionResult FundWallet()
        {
            return View();
        }
        [HttpPost]
        public IActionResult FundWallet(string id, decimal amount)
        {
            var fund = _customerService.FundWallet(id, amount);
            if (fund.Status == true)
            {
                return StatusCode(200, "Wallet Fund Successfully");
            }
            return StatusCode(406, "Unable To Fund Wallet Try Again Later ");
        }
        [HttpGet]
        public IActionResult CheckWallet(string id)
        {
            var wallet = _customerService.CheckWallet(id);
            if (wallet.Status == true)
            {
                ViewBag.Message = wallet.Message;
                return View();
            }
            return StatusCode(406, "Try Again Later ");

        }
        [HttpGet]
        public IActionResult Details(string id)
        {
            var customer = _customerService.GetById(id);
            return View(customer);
        }
            [HttpGet]
        public IActionResult GetAll()
        {
            var customer = _customerService.GetAll();
            return View(customer);
        }
        public IActionResult FoodStatus()
        {
            var food = _foodService.UpdateFoodStatus();
            return View(_foodService.GetAllFood().Data);
        }

    }
}

Controllers/OrderController.cs
using System.Security.Claims;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Food_Mania.Models.Dtos;
using Food_Mania.Models.Enum;
using Food_Mania.Models.Service.Interface;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Food_Mania.Controllers
{
    // [Route("[controller]")]
    public class OrderController : Controller
    {
        private readonly ILogger<OrderController> _logger;
        private readonly IOrderService _orderService;
        private readonly ICustomerService _customerService;
        private readonly IFoodService _foodService;

        public OrderController(ILogger<OrderController> logger, IOrderService orderService = null, ICustomerService customerService = null, IFoodService foodService = null)
        {
            _logger = logger;
            _orderService = orderService;
            _customerService = customerService;
            _foodService = foodService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
        [HttpGet]
        public IActionResult OrderFood()
        {
            return View();
        }
        [HttpPost]
        public IActionResult OrderFood(string Id, CreateOrderRequestModel model)
        {
            var customerId = HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var get = _foodService.GetById(Id);
            if (get == null || get.Data.Status == FoodStatus.NotAvailable || get.Data.Status == FoodStatus.Processing)
            {
                return StatusCode(406,"Food not available at the moment");
            }
            else
            {
                var calculate = _orderService.CalculatePrice(customerId, get.Data.Price,model.Quantity);
                if (calculate.Status == false)
                {
                    return Content(calculate.Message);
                }
                else
                {
                    var order = _orderService.CreateOrder(customerId, Id, model);
                    ViewBag.Message = order.Message + "," + calculate.Message;
                    return View();
                }
            }

        }
         public IActionResult GetAllOrder()
        {
           var get =  _orderService.ViewOrders();
            return View(get.Data);
        } 
        public IActionResult DeliveryStatus(string id)
        {
           var order =  _orderService.UpdateStatus(id);
           if(order.Status == true)
           {
            ViewBag.Message = order.Message;
             return View();
           }
           return RedirectToAction("GetAllOrder");
        }
        [ActionName("OrderProfile")]
         public IActionResult CustomerOrderProfile(string id)
        {
            var profile =  _orderService.GetOrderById(id);
            return View(profile.Data);
        }
    }
}

Controllers/StaffController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Food_Mania.Models.Dtos;
using Food_Mania.Models.Service.Interface;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Food_Mania.Controllers
{
    // [Route("[controller]")]
    public class StaffController : Controller
    {
        private readonly ILogger<StaffController> _logger;
        private readonly IStaffService _staffService;
        private readonly IFoodService _foodService;

        public StaffController(ILogger<StaffController> logger, IFoodService foodService = null, IStaffService serviceService = null)
        {
            _logger = logger;
            _foodService = foodService;
            _staffService = serviceService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(CreateStaffRequestModel model)
        {
            var add = _staffService.Create(model);
            if (add.Status == true)
            {
               TempData["message"] = add.Message;
                return RedirectToAction("Login", "User");
            }
            return StatusCode(406, "Registration Failed. Email may exist already");


        }
        [HttpGet]
        public IActionResult Update(string id)
        {
            var staff = _staffService.GetById(id);
            // var updateModel = new UpdateStaffRequestModel
            // {
            //     FirstName = staff.Data.User.FirstName,
            //     LastName = staff.Data.User.LastName,
            //     PhoneNumber = staff.Data.User.PhoneNumber,
            //     Role = staff.Data.Role,
            //     Email = staff.Data.User.Email,
            //     DateOfBirth = staff.Data.DathOfBirth,
            // };
            return View(staff.Data);
        }
        [HttpPost]
        public IActionResult Update(string id, UpdateStaffRequestModel model)
        {

            _staffService.Update(id, model);
            return RedirectToAction("");
        }
        [HttpGet]
        public IActionResult Delete(string id)
        {
            var staff = _staffService.GetById(id);
            return View(staff.Data);
        }
        [HttpPost, ActionName("Delete")]
        public IActionResult ActualDelete(string id)
        {
            var del = _staffService.Delete(id);
            return RedirectToAction("Add");
        }
        [HttpGet]
        public IActionResult Details(string id)
        {
            var staff = _staffService.GetById(id);
            return View(staff);
        }
        [ActionName("StaffProfile")]
        public IActionResult Profile(string id)
        {
            //  if(HttpContext.Session.GetString("Role") != "Admin")
            // {
            //     return RedirectToAction("AdminLogin");
            // }
            var info = _staffService.VeiwProfile(id);
            return View(info);
        }
        [HttpGet]
        public IActionResult GetAll()
        {

            return View(_staffService.GetAll());
        }


    }
}

Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Food_Mania.Models.Dtos;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Models.Service.Interface;

namespace Food_Mania.Controllers
{
    // [Route("[controller]")]
    public class UserController : Controller
    {
        private readonly ILogger<UserController> _logger;
        private readonly IUserService _userService;

        public UserController(ILogger<UserController> logger, IUserService userService = null)
        {
            _logger = logger;
            _userService = userService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
         [HttpGet]
        public IActionResult Login()
        {
            
            return View();
        }

        [HttpPost]
        public IActionResult Login(LoginUserRequestModel model)
        {
            var user = _userService.Login(model);
            
            if(!user.Status)
            {
                return View();
            }

           var claims = new List<Claim>
            {
                new Claim(ClaimTypes.Email, user.Data.Email),
                new Claim(ClaimTypes.NameIdentifier, user.Data.Id),

                new Claim(ClaimTypes.Name, user.Data.FirstName +" "+ user.Data.LastName),
                new Claim(ClaimTypes.HomePhone, user.Data.PhoneNumber)
            };

            var claimIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

            var claimsPrincipal = new ClaimsPrincipal(claimIdentity);

            HttpContext.SignInAsync(claimsPrincipal);
            
            if (user.Data.Role.ToString() == "Manager")
            {
                return RedirectToAction("Manager");
            }
           else if (user.Data.Role.ToString() == "Customer")
            {
                return RedirectToAction("Customer");
            }
          else   if (user.Data.Role.ToString() == "DeliveryMan")
            {
                return RedirectToAction("DeliveryMan");
            }
           else if (user.Data.Role.ToString() == "Cook")
            {
                return RedirectToAction("Cook");
            }
            else 
            {
                return   StatusCode(406, "Update Failed. ");
            }
        }
        public IActionResult Logout()
        {
            HttpContext.SignOutAsync();
            return RedirectToAction("Login");
        }
        public IActionResult Manager()
        {
            return View();
        }
        public IActionResult DeliveryMan()
        {
            return View();
        }
        public IActionResult Customer()
        {
            return View();
        }
        public IActionResult Cook()
        {
            return View();
        }
       
    }
}

Views/User/Customer.cshtml
@using System.Security.Claims
@{
    ViewData["Title"] = "Customer Dashboard";
}
<div class="">
    <div class="row">
        <div class="col-md-2 border" style="min-height: 520px; padding: 0px; margin: 0px">
            <img src="~/Images/manai2.jpg" alt="" height="50px" width="90px"
                style="border-radius: 20%; justify-content: center">
            <a class="dropdown-item active" asp-action="Customer" asp-controller="User">Dashboard</a>
            <a class="dropdown-item" asp-action="FundWallet" asp-controller="Customer"
                asp-route-id='@User.FindFirst(ClaimTypes.NameIdentifier)?.Value'>Fund Wallet</a>
                
            <a class="dropdown-item" asp-action="CheckWallet" asp-controller="Customer"
                asp-route-id='@User.FindFirst(ClaimTypes.NameIdentifier)?.Value'>Check Banlance</a>
            <a class="dropdown-item" asp-action="FoodStatus" asp-controller="Customer"
                asp-route-id='@User.FindFirst(ClaimTypes.NameIdentifier)?.Value'>View FoodMenu</a>
            <a class="dropdown-item" asp-action="Details" asp-controller="Customer"
                asp-route-id='@User.FindFirst(ClaimTypes.NameIdentifier)?.Value'>View profile</a>
            <a class="dropdown-item" asp-action="Update" asp-controller="Customer"
                asp-route-id='@User.FindFirst(ClaimTypes.NameIdentifier)?.Value'>update profile</a>



        </div>
        <div class="row col-md-10 pt-3">
            <div class="col-md-12 text-center">
                <h3>@ViewData["Title"]</h3>
            </div>
            <div class="col-md-12">

            </div>
        </div>
    </div>
</div>

Views/User/DeliveryMan.cshtml
@using System.Security.Claims
@{
    ViewData["Title"] = "Rider Dashboard";
}
<div class="">
    <div class="row">
        <div class="col-md-2 border" style="min-height: 520px; padding: 0px; margin: 0px">
            @* @await Html.PartialAsync("~/Views/User/Menu.cshtml") *@
            <a class="dropdown-item active" asp-action="DeliveryMan" asp-controller="User">Dashboard</a>
            
            <a class="dropdown-item" asp-action="Details" asp-controller="Staff"
                asp-route-id='@User.FindFirst(ClaimTypes.NameIdentifier)?.Value'>Profile</a>  
            <a class="dropdown-item" asp-action="GetAll" asp-controller="Food">Food Menu</a> 
            <a class="dropdown-item" asp-action="GetAllOrder" asp-controller="Order">GetAllOrder</a> 

        </div>
        <div class="row col-md-10 pt-3">
            <div class="col-md-12 text-center">
                <h3>@ViewData["Title"]</h3>
            </div>
            <div class="col-md-12">
                
            </div>
        </div>
        <li>
                @* <a asp-controller="User"  text asp-action="Manager">Back</a> *@
            </li>
    </div>
</div>

Views/User/Login.cshtml
@{
    Layout = "~/Views/Shared/_SecondLayOut.cshtml";
    
}
<body>
<div class="login-page">
    <div class="row">
        <div class="col-md-12">
            <h2>User Login</h2>
            <form method="post">

                 <div class="form-group">
                    <label for="Email">Email</label>
                    <input type="email" name="Email" id="Email" class="form-control" placeholder="Email"/>
                </div>
                 <div class="form-group">
                    <label for="Password">Password</label>
                    <input type="password" name="Password" id="password" class="form-control" placeholder="Password"/>
                </div>
                <button type="submit">Login</button>
            </form>
        </div>
    </div>
</div>
</body>

Views/User/Manager.cshtml
@{
    ViewData["Title"] = "Manager Dashboard";
}
<body>
    <style>
        body{
            background-color: cadetblue;
        }
    </style>
    <div class="">
    <div class="row">
        <div class="col-md-2 border" style="min-height: 520px; padding: 0px; margin: 0px">
            @* @await Html.PartialAsync("~/Views/User/Menu.cshtml") *@
            <a class="dropdown-item active" asp-action="Manager" asp-controller="User">Dashboard</a>
            <a class="dropdown-item" asp-action="GetAll" asp-controller="Staff">Staff List</a> 
            <a class="dropdown-item" asp-action="GetAll" asp-controller="Customer">Customer List</a> 
            <a class="dropdown-item" asp-action="AddFood" asp-controller="Food">Add Food To Menu</a> 
            <a class="dropdown-item" asp-action="GetAll" asp-controller="Food">Food Menu</a> 
            @* <a class="dropdown-item" asp-action="GetAllOrder" asp-controller="Order">GetAllOrder</a>  *@




        </div>
        <div class="row col-md-10 pt-3">
            <div class="col-md-12 text-center">
                <h3>@ViewData["Title"]</h3>
            </div>
            <div class="col-md-12">
                
            </div>
        </div>
        <li>
                @* <a asp-controller="User"  text asp-action="Manager">Back</a> *@
            </li>
    </div>
</div>
</body>

Views/User/Menu.cshtml
@using System.Security.Claims
@if(User.IsInRole("Manager"))
{
    <a class="dropdown-item active" asp-action="Manager" asp-controller="User">Dashboard</a>
    <a class="dropdown-item" asp-action="Add" asp-controller="Manager">Add Manager</a>
    <a class="dropdown-item" asp-action="List" asp-controller="Manager">Manager List</a>
    <a class="dropdown-item" asp-action="Add" asp-controller="Customer">Add Food</a>
    <a class="dropdown-item" asp-action="List" asp-controller="Customer">Customer List</a>
}
else if(User.IsInRole("Cook"))
{
    <a class="dropdown-item active" asp-action="Manager" asp-controller="User">Dashboard</a>
    @* <a class="dropdown-item" asp-action="Add" asp-controller="Customer">Create Customer</a> *@
    <a class="dropdown-item" asp-action="GetAll" asp-controller="Customer">Customer List</a>
}
else if(User.IsInRole("Customer"))
{
    <a class="dropdown-item" asp-action="Customer" asp-controller="User">Dashboard</a>
    <a class="dropdown-item" asp-action="CreditWallet" asp-controller="Wallet" asp-route-id= '@User.FindFirst(ClaimTypes.NameIdentifier)?.Value'>Credit Wallet</a>
    <a class="dropdown-item" asp-action="DebitWallet" asp-controller="Wallet" asp-route-id= '@User.FindFirst(ClaimTypes.NameIdentifier)?.Value'>Debit Wallet</a>
    <a class="dropdown-item" asp-action="Get" asp-controller="Wallet" asp-route-id= '@User.FindFirst(ClaimTypes.NameIdentifier)?.Value'>View Balance</a> 
    <a class="dropdown-item" asp-action="Get" asp-controller="Customer"  asp-route-id= '@User.FindFirst(ClaimTypes.NameIdentifier)?.Value' >View profile</a> 
    <a class="dropdown-item" asp-action="Update" asp-route-id= '@User.FindFirst(ClaimTypes.NameIdentifier)?.Value'>update profile</a>
}