Models/Entities/Order.cs
namespace Food_Mania.Models.Entities
{
    public class Order: BaseEntity
    {
        public string CustomerId { get; set; }
        public bool IsDelivered { get; set; }
        public Customer Customer { get; set; }
        public Address Address { get; set; }
        public ICollection<FoodOrder> FoodOrders { get; set; } = new HashSet<FoodOrder>();
    }
}

Controllers/OrderController.cs
using System.Security.Claims;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Food_Mania.Models.Dtos;
using Food_Mania.Models.Enum;
using Food_Mania.Models.Service.Interface;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Food_Mania.Controllers
{
    // [Route("[controller]")]
    public class OrderController : Controller
    {
        private readonly ILogger<OrderController> _logger;
        private readonly IOrderService _orderService;
        private readonly ICustomerService _customerService;
        private readonly IFoodService _foodService;

        public OrderController(ILogger<OrderController> logger, IOrderService orderService = null, ICustomerService customerService = null, IFoodService foodService = null)
        {
            _logger = logger;
            _orderService = orderService;
            _customerService = customerService;
            _foodService = foodService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
        [HttpGet]
        public IActionResult OrderFood()
        {
            return View();
        }
        [HttpPost]
        public IActionResult OrderFood(string Id, CreateOrderRequestModel model)
        {
            var customerId = HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var get = _foodService.GetById(Id);
            if (get == null || get.Data.Status == FoodStatus.NotAvailable || get.Data.Status == FoodStatus.Processing)
            {
                return StatusCode(406,"Food not available at the moment");
            }
            else
            {
                var calculate = _orderService.CalculatePrice(customerId, get.Data.Price,model.Quantity);
                if (calculate.Status == false)
                {
                    return Content(calculate.Message);
                }
                else
                {
                    var order = _orderService.CreateOrder(customerId, Id, model);
                    ViewBag.Message = order.Message + "," + calculate.Message;
                    return View();
                }
            }

        }
         public IActionResult GetAllOrder()
        {
           var get =  _orderService.ViewOrders();
            return View(get.Data);
        } 
        public IActionResult DeliveryStatus(string id)
        {
           var order =  _orderService.UpdateStatus(id);
           if(order.Status == true)
           {
            ViewBag.Message = order.Message;
             return View();
           }
           return RedirectToAction("GetAllOrder");
        }
        [ActionName("OrderProfile")]
         public IActionResult CustomerOrderProfile(string id)
        {
            var profile =  _orderService.GetOrderById(id);
            return View(profile.Data);
        }
    }
}

Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Food_Mania.Models.Dtos;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Models.Service.Interface;

namespace Food_Mania.Controllers
{
    // [Route("[controller]")]
    public class UserController : Controller
    {
        private readonly ILogger<UserController> _logger;
        private readonly IUserService _userService;

        public UserController(ILogger<UserController> logger, IUserService userService = null)
        {
            _logger = logger;
            _userService = userService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
         [HttpGet]
        public IActionResult Login()
        {
            
            return View();
        }

        [HttpPost]
        public IActionResult Login(LoginUserRequestModel model)
        {
            var user = _userService.Login(model);
            
            if(!user.Status)
            {
                return View();
            }

           var claims = new List<Claim>
            {
                new Claim(ClaimTypes.Email, user.Data.Email),
                new Claim(ClaimTypes.NameIdentifier, user.Data.Id),

                new Claim(ClaimTypes.Name, user.Data.FirstName +" "+ user.Data.LastName),
                new Claim(ClaimTypes.HomePhone, user.Data.PhoneNumber)
            };

            var claimIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

            var claimsPrincipal = new ClaimsPrincipal(claimIdentity);

            HttpContext.SignInAsync(claimsPrincipal);
            
            if (user.Data.Role.ToString() == "Manager")
            {
                return RedirectToAction("Manager");
            }
           else if (user.Data.Role.ToString() == "Customer")
            {
                return RedirectToAction("Customer");
            }
          else   if (user.Data.Role.ToString() == "DeliveryMan")
            {
                return RedirectToAction("DeliveryMan");
            }
           else if (user.Data.Role.ToString() == "Cook")
            {
                return RedirectToAction("Cook");
            }
            else 
            {
                return   StatusCode(406, "Update Failed. ");
            }
        }
        public IActionResult Logout()
        {
            HttpContext.SignOutAsync();
            return RedirectToAction("Login");
        }
        public IActionResult Manager()
        {
            return View();
        }
        public IActionResult DeliveryMan()
        {
            return View();
        }
        public IActionResult Customer()
        {
            return View();
        }
        public IActionResult Cook()
        {
            return View();
        }
       
    }
}

Views/Order/DeliveryStatus.cshtml
@using Food_Mania.Models.Dtos
@model OrderDto

<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
@if (ViewBag.Message != null)
{
    <h2>@ViewBag.Message</h2>
}

<body>
    <div>
        <div>
            <div>
                <label>
                    @* DELIVERYSTATUS:@Model.IsDelivered *@
                </label>
           
    </div>


    <style>
        body {
            background-color: rgb(50, 112, 133);
            font-size: large;
            font-weight: 900;
            font-family: Georgia, 'Times New Roman', Times, serif;
        }
    </style>
    </div>
</body>
<a class="btn-primary btn" asp-controller="Order" text asp-action="GetAllOrder">Back</a>

Views/Order/GetAllOrder.cshtml
@using Food_Mania.Models.Dtos

@model IEnumerable<Models.Dtos.FoodOrderDto>
    <link rel="stylesheet" href="~/css/foods.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    @if (@Model == null || @Model.Count() == 0)
    {
      <h1>No Orders yet</h1>
    }
    <div class="images">
           @foreach (var food in @Model)
        {
         <div class="post-image">
            @if (food.FoodDto.Status != Food_Mania.Models.Enum.FoodStatus.NotAvailable)
            {   
                    <img src="~/food/images/@food.FoodDto.Image" alt="food image">
                    <h6>TYPE: @food.FoodDto.Type</h6>
                    <p>DESCRIPTION: @food.FoodDto.Description</p>
                    <p>PRICE: ₦ @food.FoodDto.Price</p>
                    <p>STATUS: @food.FoodDto.Status</p>
                    <p>ORDERED TIME: @food.OrderDto.CreatedAt</p>
                    if (food.OrderDto.IsDelivered == true)
                    {
                       <div class="btn-group">
                                <a class="btn-warning btn" asp-action="OrderProfile" asp-controller="Order" asp-route-id=@food.OrderDto.Id></a>        
                                <button class="btn-danger btn" asp-action="DeliveryStatus" asp-controller="Order" asp-route-Id=@food.OrderDto.Id disabled>Mark as Delivered</button>
                            </div>              
                    }
                    else
                    {
                            <div class="btn-group">
                                <a class="btn-warning btn" asp-action="OrderProfile" asp-controller="Order" asp-route-id=@food.OrderDto.Id>Customer</a>
                                <a class="btn-danger btn" asp-action="DeliveryStatus" asp-controller="Order" asp-route-id=@food.OrderDto.Id >Mark as Delivered</a>
                            </div>              
                    }
            }
             </div>
        }
@* <a class="btn-primary btn" asp-controller="User" text asp-action="Manager">Back</a> *@

    </div>

Views/Order/OrderFood.cshtml
@using Food_Mania.Models.Dtos
@model OrderDto
@{
    Layout = "~/Views/Shared/_SecondLayOut.cshtml";
}
@if (ViewBag.Message != null)
{
    <h2>@ViewBag.Message</h2>
}
<div class="row">
    <div class="col-md-12">
        <h2>OrderFood</h2>
        <form asp-action="OrderFood">
            <div class="form-group">
                <label for="Quantity">Quantity</label>
                <input type="number" name="Quantity" id="Quantity" class="form-control" />
            </div>
            <div class="form-group">
                <label for="Street">Street</label>
                <input for="Street" type="text" name="Street" id="Street" class="form-control" />
            </div>
            <div class="form-group">
                <label for="City" class="control-label">City</label>
                <input type="text" name="City" id="City" class="form-control" />
         
            <div class="form-group">
                <label for="State">State</label>
                <input type="text" name="State" id="State" class="form-control" />
            </div>
            <div>
                <label for="State">Sure</label>
                <input type="text" name="" id="" class="form-control"
                    placeholder="Are you sure you want to place this order" />
            </div>
            <button type="submit">Submit</button>
        </form>        

<a class="btn-primary btn" asp-controller="Customer" text asp-action="FoodStatus">Back</a>

Views/Order/OrderProfile.cshtml
@using Food_Mania.Models.Dtos
@model OrderDto
@{

}
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

<body>
    <div>
        <div>
            <div>
        <label>
        UserName:@Model.CustomerDto.UserName
    </label>
    </div>
    
     <div>
        <label>
        Email:@Model.CustomerDto.Users.Email
    </label>
    </div>
    <div>
        <label>
        PhoneNumber:@Model.CustomerDto.Users.PhoneNumber
    </label>
    </div>

    <div>
        <label>
        GENDER:@Model.CustomerDto.Gender
    </label>
    </div>

   
    <div>
        <label>
        STREET:@Model.Street
    </label>
    </div>
    <div>
        <label>
        CITY:@Model.State
    </label>
    </div>
    <div>
        <label>
        STATE:@Model.City
    </label>
    </div>
        </div>
         

        <style>
            body {
                background-color: rgb(50, 112, 133);
                font-size: large;
                font-weight: 900;
                font-family: Georgia, 'Times New Roman', Times, serif;
            }
        </style>
    </div>
</body>
<a class="btn-primary btn" asp-controller="Order" text asp-action="GetAllOrder">Back</a>